[2025-01-23T13:42:42.993+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_airflow.etl_task manual__2025-01-23T12:14:19.972456+00:00 [queued]>
[2025-01-23T13:42:42.998+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_airflow.etl_task manual__2025-01-23T12:14:19.972456+00:00 [queued]>
[2025-01-23T13:42:42.998+0000] {taskinstance.py:1361} INFO - Starting attempt 13 of 13
[2025-01-23T13:42:43.005+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): etl_task> on 2025-01-23 12:14:19.972456+00:00
[2025-01-23T13:42:43.007+0000] {standard_task_runner.py:57} INFO - Started process 570 to run task
[2025-01-23T13:42:43.009+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'hello_***', 'etl_task', 'manual__2025-01-23T12:14:19.972456+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmptzxx28ke']
[2025-01-23T13:42:43.011+0000] {standard_task_runner.py:85} INFO - Job 23: Subtask etl_task
[2025-01-23T13:42:43.040+0000] {task_command.py:415} INFO - Running <TaskInstance: hello_airflow.etl_task manual__2025-01-23T12:14:19.972456+00:00 [running]> on host d2c53ae28a1f
[2025-01-23T13:42:43.085+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hello_***' AIRFLOW_CTX_TASK_ID='etl_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-23T12:14:19.972456+00:00' AIRFLOW_CTX_TRY_NUMBER='13' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-23T12:14:19.972456+00:00'
[2025-01-23T13:42:43.086+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-23T13:42:43.086+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/etl.py']
[2025-01-23T13:42:43.091+0000] {subprocess.py:86} INFO - Output:
[2025-01-23T13:42:43.146+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-01-23T13:42:43.146+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/etl.py", line 1, in <module>
[2025-01-23T13:42:43.146+0000] {subprocess.py:93} INFO -     from pyspark.sql import SparkSession,functions as func
[2025-01-23T13:42:43.146+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'pyspark'
[2025-01-23T13:42:43.148+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-01-23T13:42:43.154+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-23T13:42:43.156+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=hello_***, task_id=etl_task, execution_date=20250123T121419, start_date=20250123T134242, end_date=20250123T134243
[2025-01-23T13:42:43.165+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 23 for task etl_task (Bash command failed. The command returned a non-zero exit code 1.; 570)
[2025-01-23T13:42:43.182+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-23T13:42:43.194+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
